version: "3"
services:
  api:
    image: "node:8"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api/nw-api:/home/node/app
    ports:
      - 8000:3000
    command: bash -c "npm install && npm start"

  db:
    image: postgres:11.1
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=new-wicam
      - POSTGRES_USER=honeykers
      - POSTGRES_PASSWORD=barkthefuture
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    # healthcheck:
    #   test: "pg_isready -h localhost -p 5432 -q -U postgres"
    #   interval: 3s
    #   timeout: 1s
    #   retries: 10
    ports:
      - 5432:5432

  webvserver:
    image: nginx:latest
    volumes:
    # - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    # - ./nginx:/etc/nginx/conf.d
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    # command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
